# Generated by Django 5.1.5 on 2025-10-09 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="客戶名稱"),
                ),
                (
                    "internal_code",
                    models.CharField(
                        help_text="用於系統內部識別的唯一代碼",
                        max_length=50,
                        unique=True,
                        verbose_name="內部代碼",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, verbose_name="聯絡人"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="聯絡Email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="聯絡電話"),
                ),
                ("address", models.TextField(blank=True, verbose_name="地址")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否啟用")),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存放客戶特定的設定（如品牌顏色、Logo URL等）",
                        verbose_name="客戶設定",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "admin_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="managed_clients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="管理員帳號",
                    ),
                ),
            ],
            options={
                "verbose_name": "客戶",
                "verbose_name_plural": "客戶管理",
                "ordering": ["name"],
            },
        ),
    ]
