# Generated by Django 5.1.5 on 2025-10-21 11:05

import Client.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_sid",
                    models.CharField(max_length=20, unique=True, verbose_name="模組 ID"),
                ),
                ("module_name", models.CharField(max_length=50, verbose_name="模組名稱")),
                ("description", models.TextField(blank=True, verbose_name="模組描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否啟用")),
            ],
            options={
                "verbose_name": "模組資訊",
                "verbose_name_plural": "2-1. 模組資訊",
                "ordering": ["module_sid"],
            },
        ),
        migrations.CreateModel(
            name="PageInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_sid",
                    models.CharField(max_length=20, unique=True, verbose_name="頁面 ID"),
                ),
                ("page_name", models.CharField(max_length=50, verbose_name="頁面名稱")),
                ("description", models.TextField(blank=True, verbose_name="頁面描述")),
            ],
            options={
                "verbose_name": "頁面資訊",
                "verbose_name_plural": "3-1. 頁面資訊",
                "ordering": ["page_sid"],
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["name"],
                "verbose_name": "客戶",
                "verbose_name_plural": "1. 客戶管理",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="AIService",
            field=models.BooleanField(default=False, verbose_name="AI 客服系統"),
        ),
        migrations.AddField(
            model_name="client",
            name="CRM",
            field=models.BooleanField(default=False, verbose_name="顧客管理系統 (CRM)"),
        ),
        migrations.AddField(
            model_name="client",
            name="ETicket",
            field=models.BooleanField(default=False, verbose_name="電子票券系統"),
        ),
        migrations.AddField(
            model_name="client",
            name="ImageGeneration",
            field=models.BooleanField(default=False, verbose_name="AI 圖片系統"),
        ),
        migrations.AddField(
            model_name="client",
            name="MGM",
            field=models.BooleanField(
                default=False,
                help_text="Member Get Member 推薦系統",
                verbose_name="推薦系統 (MGM)",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="QPOS",
            field=models.BooleanField(default=False, verbose_name="POS 系統"),
        ),
        migrations.AddField(
            model_name="client",
            name="Reserve",
            field=models.BooleanField(default=False, verbose_name="預約系統"),
        ),
        migrations.AddField(
            model_name="client",
            name="Sale",
            field=models.BooleanField(default=False, verbose_name="分潤系統"),
        ),
        migrations.AddField(
            model_name="client",
            name="Shop",
            field=models.BooleanField(default=False, verbose_name="商城系統"),
        ),
        migrations.AddField(
            model_name="client",
            name="company_address",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="公司地址"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="company_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="公司 Email"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="company_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="公司全名"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="company_phone",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="公司電話"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="company_tax_id",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="公司統編"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="logo_url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Logo URL"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="password",
            field=models.CharField(
                blank=True, help_text="客戶登入密碼（加密儲存）", max_length=128, verbose_name="密碼"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="program",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="方案名稱"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="sales",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="業務負責人"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="service_end_date",
            field=models.DateTimeField(
                default=Client.models.one_month_later, verbose_name="服務結束日期"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="service_start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="服務開始日期"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="聯絡 Email"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="internal_code",
            field=models.CharField(
                help_text="用於系統內部識別的唯一代碼（client_sid）",
                max_length=50,
                unique=True,
                verbose_name="內部代碼",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(
                help_text="客戶的顯示名稱", max_length=200, verbose_name="客戶名稱"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="存放客戶特定的設定（如品牌顏色、其他配置等）",
                verbose_name="客戶設定",
            ),
        ),
        migrations.CreateModel(
            name="ModuleSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否啟用")),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="此客戶對該模組的特定配置",
                        verbose_name="模組特定設定",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_settings",
                        to="Client.client",
                        verbose_name="客戶",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_settings",
                        to="Client.moduleinfo",
                        verbose_name="模組",
                    ),
                ),
            ],
            options={
                "verbose_name": "模組設定",
                "verbose_name_plural": "2-2. 模組設定",
                "ordering": ["client", "module"],
                "unique_together": {("client", "module")},
            },
        ),
        migrations.CreateModel(
            name="PageColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color_primary",
                    models.CharField(
                        blank=True,
                        help_text="例如：#1E40AF",
                        max_length=9,
                        null=True,
                        verbose_name="主色",
                    ),
                ),
                (
                    "color_secondary",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="副色"
                    ),
                ),
                (
                    "color_tertiary",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="強調色"
                    ),
                ),
                (
                    "color_background",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="背景色"
                    ),
                ),
                (
                    "color_text",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="文字色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_colors",
                        to="Client.client",
                        verbose_name="客戶",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_colors",
                        to="Client.pageinfo",
                        verbose_name="頁面",
                    ),
                ),
            ],
            options={
                "verbose_name": "頁面顏色設定",
                "verbose_name_plural": "3-2. 頁面顏色設定",
                "ordering": ["client", "page"],
                "unique_together": {("client", "page")},
            },
        ),
    ]
