# Generated by Django 5.1.5 on 2025-10-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0002_moduleinfo_pageinfo_alter_client_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="address",
        ),
        migrations.RemoveField(
            model_name="client",
            name="admin_users",
        ),
        migrations.RemoveField(
            model_name="client",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="client",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="client",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="client",
            name="settings",
        ),
    ]
