# Generated by Django 5.1.5 on 2025-11-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0003_remove_client_address_remove_client_admin_users_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="AIService",
        ),
        migrations.RemoveField(
            model_name="client",
            name="CRM",
        ),
        migrations.RemoveField(
            model_name="client",
            name="ETicket",
        ),
        migrations.RemoveField(
            model_name="client",
            name="ImageGeneration",
        ),
        migrations.RemoveField(
            model_name="client",
            name="MGM",
        ),
        migrations.RemoveField(
            model_name="client",
            name="QPOS",
        ),
        migrations.RemoveField(
            model_name="client",
            name="Reserve",
        ),
        migrations.RemoveField(
            model_name="client",
            name="Sale",
        ),
        migrations.RemoveField(
            model_name="client",
            name="Shop",
        ),
    ]
