# Generated by Django 5.1.5 on 2026-04-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0004_remove_client_aiservice_remove_client_crm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="bank_account_holder",
            field=models.CharField(
                blank=True,
                default="",
                help_text="收款戶名",
                max_length=100,
                verbose_name="帳戶戶名",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="bank_account_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="收款帳號",
                max_length=50,
                verbose_name="銀行帳號",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="bank_branch",
            field=models.CharField(
                blank=True,
                default="",
                help_text="例如：信義分行",
                max_length=100,
                verbose_name="分行名稱",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="bank_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="收款用銀行名稱，例如：台灣銀行",
                max_length=100,
                verbose_name="銀行名稱",
            ),
        ),
    ]
