# Generated by Django 5.1.5 on 2026-06-26 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0005_client_bank_account_holder_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("page", "頁面內容"),
                            ("offer", "限定優惠"),
                            ("article", "攻略/文章"),
                            ("faq", "常見問題"),
                            ("review", "學生評價"),
                            ("media", "攝影作品"),
                            ("social", "社群動態"),
                            ("setting", "區塊設定"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="內容類型",
                    ),
                ),
                (
                    "location_key",
                    models.CharField(
                        db_index=True,
                        help_text="例如 homepage.reviews、news.offers、guides.preparation",
                        max_length=80,
                        verbose_name="顯示位置",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="標題"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="副標題"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="摘要"),
                ),
                ("body", models.TextField(blank=True, default="", verbose_name="內容")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="圖片網址"
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="連結網址"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="來源"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="外部 ID"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="標籤")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="其他設定"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "進行中"),
                            ("ended", "已結束"),
                            ("hidden", "隱藏"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="開始時間"),
                ),
                (
                    "end_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="結束時間"),
                ),
                ("display_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_pinned", models.BooleanField(default=False, verbose_name="置頂")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_contents",
                        to="Client.client",
                        verbose_name="客戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "官網內容",
                "verbose_name_plural": "4-1. 官網內容",
                "ordering": [
                    "content_type",
                    "location_key",
                    "-is_pinned",
                    "display_order",
                    "-created_at",
                ],
                "indexes": [
                    models.Index(
                        fields=["client", "content_type", "location_key", "status"],
                        name="Client_site_client__7122e6_idx",
                    ),
                    models.Index(
                        fields=["client", "end_at"],
                        name="Client_site_client__0ccf48_idx",
                    ),
                ],
            },
        ),
    ]
