# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0006_sitecontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontent",
            name="image_url",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="圖片網址"),
        ),
        migrations.AlterField(
            model_name="sitecontent",
            name="link_url",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="連結網址"),
        ),
    ]
