# Generated by Django 5.1.5 on 2025-08-26 11:34

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Coach", "0001_initial"),
        ("Courses", "0001_initial"),
        ("Resorts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_preferred_coach", models.BooleanField(default=False)),
                ("need_equipment", models.BooleanField(default=False)),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rentWithoutyourself", "自行租借不須協助"),
                            ("ownWithoutAssistance", "自備裝備不須協助"),
                            ("assistDuringCourse", "課程時間內協助"),
                            ("purchaseAssistanceTime", "加購協助時間"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="租借裝備",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("zh", "中文"), ("en", "英文"), ("yue", "粵語")],
                        default="zh",
                        max_length=10,
                    ),
                ),
                (
                    "max_ability_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_exp", "無經驗"),
                            ("entry", "入門"),
                            ("basic", "初階"),
                            ("intermediate", "中階"),
                            ("advanced", "高階"),
                            ("expert", "專家"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="最高滑雪能力",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "創建預約"),
                            ("cancelled", "已取消"),
                            ("deleted", "已刪除"),
                            ("auto_assignment_failed", "無法自動排定教練"),
                            ("manual_assignment_needed", "需人工排定教練"),
                            ("auto_assigned", "已自動排定教練"),
                            ("manually_assigned", "人工手動排定教練"),
                            ("pending_coach_confirmation", "等待教練確認"),
                            ("form_filled", "已填表單"),
                            ("completed", "已完成"),
                        ],
                        default="created",
                        max_length=30,
                        verbose_name="預約狀態",
                    ),
                ),
                ("mdt_add", models.DateTimeField(auto_now_add=True, null=True)),
                ("number_of_people", models.IntegerField(default=0, verbose_name="人數")),
                (
                    "equipment_rental_fee",
                    models.PositiveIntegerField(default=0, verbose_name="租借裝備費用"),
                ),
                (
                    "language_fee",
                    models.PositiveIntegerField(default=0, verbose_name="語言指定費用"),
                ),
                (
                    "coach_fee",
                    models.PositiveIntegerField(default=0, verbose_name="教練指定費用"),
                ),
                (
                    "course_fee",
                    models.PositiveIntegerField(default=0, verbose_name="課程費用"),
                ),
                (
                    "total_fee",
                    models.PositiveIntegerField(default=0, verbose_name="總和費用"),
                ),
                (
                    "payment_amount",
                    models.PositiveIntegerField(default=0, verbose_name="付款費用"),
                ),
                (
                    "course_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Courses.coursetype",
                        verbose_name="課程類型",
                    ),
                ),
                (
                    "preferred_coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Coach.coach",
                    ),
                ),
                (
                    "rejected_coaches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rejected_reservations",
                        to="Coach.coach",
                        verbose_name="拒絕過的教練",
                    ),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Resorts.resorts",
                        verbose_name="雪場",
                    ),
                ),
            ],
            options={
                "verbose_name": "預約",
                "verbose_name_plural": "2-1.預約列表",
            },
        ),
        migrations.CreateModel(
            name="MemberDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filled_by",
                    models.CharField(
                        choices=[("coach", "教練"), ("user", "使用者")],
                        default="user",
                        max_length=10,
                        verbose_name="填寫人",
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        choices=[
                            ("4-6y", "幼兒4-6y"),
                            ("7-12y", "兒童7-12y"),
                            ("13-18y", "青少年13-18y"),
                            ("19-24y", "成人19-24y"),
                            ("25-35y", "成人25-35y"),
                            ("36-45y", "成人36-45y"),
                            ("46-55y", "成人46-55y"),
                            ("56y以上", "56y以上"),
                        ],
                        default="19-24y",
                        max_length=10,
                        verbose_name="年齡區間",
                    ),
                ),
                (
                    "snowboard_skills",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("無經驗", "無經驗"),
                            ("室內滑雪機橫滑", "室內滑雪機橫滑"),
                            ("室內滑雪機Healside落葉飄", "室內滑雪機Healside落葉飄"),
                            ("室內滑雪機C turn", "室內滑雪機C turn"),
                            ("室內滑雪機S turn", "室內滑雪機S turn"),
                            ("室內滑雪機Toeside落葉飄", "室內滑雪機Toeside落葉飄"),
                            ("小叮噹橫滑", "小叮噹橫滑"),
                            ("小叮噹Healside落葉飄", "小叮噹Healside落葉飄"),
                            ("小叮噹Toeside落葉飄", "小叮噹Toeside落葉飄"),
                            ("小叮噹 C turn", "小叮噹 C turn"),
                            ("小叮噹S turn", "小叮噹S turn"),
                            ("雪場橫滑", "雪場橫滑"),
                            ("雪場Healside落葉飄", "雪場Healside落葉飄"),
                            ("雪場Toeside落葉飄", "雪場Toeside落葉飄"),
                            ("雪場C turn", "雪場C turn"),
                            ("雪場S turn", "雪場S turn"),
                            ("雪場綠線順滑", "雪場綠線順滑"),
                            ("雪場藍(紅)線順滑", "雪場藍(紅)線順滑"),
                            ("雪場黑線順滑", "雪場黑線順滑"),
                            ("雪場樹林", "雪場樹林"),
                            ("雪場界外", "雪場界外"),
                        ],
                        max_length=208,
                        null=True,
                        verbose_name="單板程度",
                    ),
                ),
                (
                    "ski_skills",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("無經驗", "無經驗"),
                            ("室內滑雪機全制動煞車", "室內滑雪機全制動煞車"),
                            ("室內滑雪機全制動轉彎", "室內滑雪機全制動轉彎"),
                            ("室內滑雪機半制動轉彎", "室內滑雪機半制動轉彎"),
                            ("室內滑雪機並腿轉彎", "室內滑雪機並腿轉彎"),
                            ("小叮噹全制動煞車", "小叮噹全制動煞車"),
                            ("小叮噹全制動轉彎", "小叮噹全制動轉彎"),
                            ("小叮噹半制動轉彎", "小叮噹半制動轉彎"),
                            ("小叮噹並腿轉彎", "小叮噹並腿轉彎"),
                            ("雪場全制動煞車", "雪場全制動煞車"),
                            ("雪場全制動轉彎", "雪場全制動轉彎"),
                            ("雪場半制動轉彎", "雪場半制動轉彎"),
                            ("雪場並腿轉彎", "雪場並腿轉彎"),
                            ("雪場綠線順滑", "雪場綠線順滑"),
                            ("雪場藍(紅)線順滑", "雪場藍(紅)線順滑"),
                            ("雪場黑線順滑", "雪場黑線順滑"),
                            ("雪場樹林", "雪場樹林"),
                            ("雪場界外", "雪場界外"),
                        ],
                        max_length=146,
                        null=True,
                        verbose_name="雙板程度",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="booking.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "學員程度表單",
                "verbose_name_plural": "2-3.學員程度表單",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_type", models.CharField(default="", max_length=50)),
                ("course_name", models.CharField(default="", max_length=50)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="booking.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "預約課程",
                "verbose_name_plural": "2-2.預約課程",
            },
        ),
        migrations.CreateModel(
            name="ReservationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="預約分組名稱"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "預約分組",
                "verbose_name_plural": "2-0.預約分組",
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="booking.reservationgroup",
                verbose_name="所屬分組",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "未付款"),
                            ("pending", "待確認付款"),
                            ("paid", "已付款"),
                            ("expired", "付款時間已過期"),
                            ("refunded", "已退款"),
                        ],
                        default="unpaid",
                        max_length=10,
                        verbose_name="付款狀態",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("newebpay", "藍新支付"), ("TT", "匯款")],
                        default="TT",
                        max_length=20,
                        verbose_name="付款方式",
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="匯款帳號"
                    ),
                ),
                ("DataJSON", models.JSONField(default=dict)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="付款用戶",
                    ),
                ),
                (
                    "reservation_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="booking.reservationgroup",
                        verbose_name="關聯預約分組",
                    ),
                ),
            ],
            options={
                "verbose_name": "付款紀錄",
                "verbose_name_plural": "2-4.付款紀錄",
            },
        ),
    ]
