# Generated by Django 5.1.5 on 2025-09-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coursekit", "0005_alter_coursepricing_options_and_more"),
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="course_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Coursekit.coursetype",
                verbose_name="課程類型",
            ),
        ),
    ]
