# Generated by Django 5.1.5 on 2026-09-02 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resorts', '0008_campus_operatingpolicy_paymentaccount_and_more'),
        ('booking', '0007_update_ability_levels_to_numeric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationgroup',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_groups', to='Resorts.campus', verbose_name='訂單校區'),
        ),
        migrations.AddField(
            model_name='reservationgroup',
            name='line_group_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='LINE 群組連結'),
        ),
        migrations.AddField(
            model_name='reservationgroup',
            name='marketing_source',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='行銷來源'),
        ),
        migrations.AddField(
            model_name='reservationgroup',
            name='marketing_source_detail',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='行銷來源說明'),
        ),
        migrations.AddField(
            model_name='reservationgroup',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='訂單編號'),
        ),
        migrations.AddField(
            model_name='reservationgroup',
            name='referral_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_reservation_groups', to=settings.AUTH_USER_MODEL, verbose_name='介紹人'),
        ),
    ]
