# Generated by Django 5.1.5 on 2026-09-02 19:06

import booking.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_alter_sitecontent_image_url_and_more'),
        ('Coach', '0012_payrollstatement_payrollline_coachpayrule_and_more'),
        ('Coursekit', '0016_coursetemplate_billing_mode_and_more'),
        ('Resorts', '0009_remove_operatingpolicy_unique_client_default_operating_policy'),
        ('booking', '0009_initialize_campus_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetail',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarded_member_details', to=settings.AUTH_USER_MODEL, verbose_name='家長帳號'),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='insurance_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='保險資料完成時間'),
        ),
        migrations.AddField(
            model_name='memberdetail',
            name='waiver_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='聲明書完成時間'),
        ),
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='付款保留到期時間'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='Resorts.paymentaccount', verbose_name='收款帳戶'),
        ),
        migrations.AddField(
            model_name='reservationgroup',
            name='source_country',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='下單國家'),
        ),
        migrations.AddField(
            model_name='reservationgroup',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='下單 IP'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('newebpay', '藍新支付'), ('TT', '匯款'), ('credit_card', '信用卡'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay')], default='TT', max_length=20, verbose_name='付款方式'),
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', '待處理'), ('approved', '已核准'), ('rejected', '已拒絕'), ('refunded', '已退款')], default='requested', max_length=20)),
                ('reason', models.CharField(choices=[('schedule', '行程變更'), ('health', '健康因素'), ('weather', '天候因素'), ('duplicate', '重複訂單'), ('other', '其他')], max_length=30)),
                ('reason_note', models.TextField(blank=True, default='')),
                ('original_amount', models.PositiveIntegerField(default=0)),
                ('days_before', models.IntegerField(default=0)),
                ('refund_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('handling_fee_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('refund_amount', models.PositiveIntegerField(default=0)),
                ('refund_bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('refund_account_number', models.CharField(blank=True, default='', max_length=100)),
                ('refund_account_holder', models.CharField(blank=True, default='', max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellation_requests', to='booking.reservationgroup')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cancellations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_assessment', models.JSONField(blank=True, default=dict)),
                ('coach_assessment', models.JSONField(blank=True, default=dict)),
                ('learning_progress', models.JSONField(blank=True, default=dict)),
                ('trail_names', models.JSONField(blank=True, default=list)),
                ('coach_notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='booking.booking')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_evaluations', to='Coach.coach')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='booking.memberdetail')),
            ],
            options={
                'unique_together': {('booking', 'member')},
            },
        ),
        migrations.CreateModel(
            name='CourseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', '照片'), ('video', '影片')], max_length=10)),
                ('url', models.URLField(max_length=800)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('is_public', models.BooleanField(default=False, verbose_name='可於官網顯示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='booking.courseevaluation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(default=booking.models.referral_code_default, max_length=20, unique=True, verbose_name='專屬推薦碼')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='點數')),
                ('level', models.CharField(choices=[('new', '新會員'), ('alumni', '舊生'), ('silver', '銀級'), ('gold', '金級')], default='new', max_length=20, verbose_name='會員等級')),
                ('alumni_verified', models.BooleanField(default=False, verbose_name='舊生已審核')),
                ('previous_points', models.PositiveIntegerField(default=0, verbose_name='手動補登點數')),
                ('line_user_id', models.CharField(blank=True, default='', max_length=100, verbose_name='LINE 帳號')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snowland_member_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event', models.CharField(choices=[('order_created', '訂單成立'), ('payment_confirmed', '付款完成'), ('pre_course', '課前提醒'), ('missing_documents', '資料未完成'), ('line_group', 'LINE 群組邀請'), ('evaluation_due', '評量未完成')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('line', 'LINE'), ('in_app', '站內通知')], max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField()),
                ('days_before', models.IntegerField(default=0, help_text='課前幾天；事件立即發送請填 0')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='Resorts.campus')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='Client.client')),
                ('course_templates', models.ManyToManyField(blank=True, related_name='notification_templates', to='Coursekit.coursetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', '已排程'), ('sent', '已發送'), ('failed', '發送失敗'), ('cancelled', '已取消')], default='scheduled', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='booking.reservationgroup')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='booking.notificationtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='StaffBookingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('cart_snapshot', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_booking_links', to='Resorts.campus')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_booking_links', to='Client.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_booking_links', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_staff_booking_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='版本')),
                ('change_type', models.CharField(choices=[('create', '建立'), ('modify', '修改'), ('add', '追加'), ('reduce', '追減'), ('cancel', '取消')], default='modify', max_length=20)),
                ('snapshot', models.JSONField(default=dict, verbose_name='當時訂單內容')),
                ('difference_amount', models.IntegerField(default=0, verbose_name='與上一版差額')),
                ('reason', models.TextField(blank=True, default='', verbose_name='修改原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_revisions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='booking.reservationgroup', verbose_name='訂單')),
            ],
            options={
                'ordering': ['group', '-version'],
                'unique_together': {('group', 'version')},
            },
        ),
    ]
