# Generated by Django 5.1.5 on 2025-09-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Resorts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="季節期間名稱")),
                (
                    "season_type",
                    models.CharField(
                        choices=[("peak", "旺季"), ("off", "淡季")],
                        max_length=10,
                        verbose_name="季節類型",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="開始日期")),
                ("end_date", models.DateField(verbose_name="結束日期")),
            ],
            options={
                "verbose_name": "6. 季節定價設定",
                "verbose_name_plural": "6. 季節定價設定",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如：單板 Snowboard",
                        max_length=100,
                        verbose_name="課程大類名稱",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="數字越小，排序越前面", verbose_name="顯示順序"
                    ),
                ),
                (
                    "available_resorts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="available_categories",
                        to="Resorts.resorts",
                        verbose_name="可開設雪場",
                    ),
                ),
            ],
            options={
                "verbose_name": "1. 課程大類",
                "verbose_name_plural": "1. 課程大類",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CourseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如：4小時初學者課程", max_length=100, verbose_name="課程模板名稱"
                    ),
                ),
                (
                    "duration_hours",
                    models.PositiveIntegerField(
                        help_text="例如：4", verbose_name="課程時長(小時)"
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        default=6, help_text="此課程模板的預設人數限制", verbose_name="預設最大容量"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用此課程模板"),
                ),
                (
                    "booking_open_time",
                    models.TimeField(help_text="例如：09:00", verbose_name="開放預約時間"),
                ),
                (
                    "booking_close_time",
                    models.TimeField(help_text="例如：17:00", verbose_name="關閉預約時間"),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bound_courses",
                        to="Resorts.resorts",
                        verbose_name="綁定雪場",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. 課程模板",
                "verbose_name_plural": "3. 課程模板",
                "ordering": [
                    "course_type__category__display_order",
                    "course_type__display_order",
                    "duration_hours",
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="例如：09:00", verbose_name="開始時間"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="例如：13:00", verbose_name="結束時間"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用此時段"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="Coursekit.coursetemplate",
                        verbose_name="所屬課程模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "4. 上課時段",
                "verbose_name_plural": "4. 上課時段",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="CourseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如：初學者課程", max_length=100, verbose_name="課程類型名稱"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="數字越小，排序越前面", verbose_name="顯示順序"
                    ),
                ),
                (
                    "available_resorts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="available_course_types",
                        to="Resorts.resorts",
                        verbose_name="可開設雪場",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="Coursekit.coursecategory",
                        verbose_name="所屬課程大類",
                    ),
                ),
            ],
            options={
                "verbose_name": "2. 課程類型",
                "verbose_name_plural": "2. 課程類型",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="coursetemplate",
            name="course_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="Coursekit.coursetype",
                verbose_name="所屬課程類型",
            ),
        ),
        migrations.CreateModel(
            name="CoursePricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_price_off_peak",
                    models.PositiveIntegerField(
                        help_text="淡季時1人的基礎價格", verbose_name="淡季基礎價格"
                    ),
                ),
                (
                    "peak_season_surcharge",
                    models.PositiveIntegerField(
                        help_text="旺季時額外加價的金額", verbose_name="旺季加價"
                    ),
                ),
                (
                    "additional_person_fee",
                    models.PositiveIntegerField(
                        help_text="每增加1人需額外支付的費用", verbose_name="每增加一人費用"
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        help_text="此定價策略的最大人數限制", verbose_name="最大容量"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否啟用")),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_pricing",
                        to="Resorts.resorts",
                        verbose_name="適用雪場",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_options",
                        to="Coursekit.coursetemplate",
                        verbose_name="所屬課程模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "5. 課程定價",
                "verbose_name_plural": "5. 課程定價",
                "ordering": ["template", "resort"],
                "unique_together": {("template", "resort")},
            },
        ),
    ]
