# Generated by Django 5.1.5 on 2025-09-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coursekit", "0001_initial"),
        ("Resorts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursetemplate",
            name="booking_close_time",
        ),
        migrations.RemoveField(
            model_name="coursetemplate",
            name="booking_open_time",
        ),
        migrations.RemoveField(
            model_name="coursetemplate",
            name="resort",
        ),
        migrations.AddField(
            model_name="coursetemplate",
            name="booking_close_date",
            field=models.DateField(
                blank=True, help_text="例如：2024-03-31", null=True, verbose_name="關閉預約日期"
            ),
        ),
        migrations.AddField(
            model_name="coursetemplate",
            name="booking_open_date",
            field=models.DateField(
                blank=True, help_text="例如：2024-12-01", null=True, verbose_name="開放預約日期"
            ),
        ),
        migrations.AddField(
            model_name="coursetemplate",
            name="resorts",
            field=models.ManyToManyField(
                blank=True,
                related_name="bound_courses",
                to="Resorts.resorts",
                verbose_name="綁定雪場",
            ),
        ),
    ]
