# Generated by Django 5.1.5 on 2025-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coursekit", "0002_remove_coursetemplate_booking_close_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursetemplate",
            name="booking_close_date",
        ),
        migrations.RemoveField(
            model_name="coursetemplate",
            name="booking_open_date",
        ),
        migrations.AddField(
            model_name="coursetemplate",
            name="course_end_date",
            field=models.DateField(
                blank=True, help_text="例如：2024-03-31", null=True, verbose_name="課程結束日期"
            ),
        ),
        migrations.AddField(
            model_name="coursetemplate",
            name="course_start_date",
            field=models.DateField(
                blank=True, help_text="例如：2024-12-01", null=True, verbose_name="課程開始日期"
            ),
        ),
    ]
