# Generated by Django 5.1.5 on 2025-09-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coursekit", "0003_remove_coursetemplate_booking_close_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetemplate",
            name="booking_close_date",
            field=models.DateField(
                blank=True, help_text="例如：2024-03-31", null=True, verbose_name="關閉預約日期"
            ),
        ),
        migrations.AddField(
            model_name="coursetemplate",
            name="booking_open_date",
            field=models.DateField(
                blank=True, help_text="例如：2024-12-01", null=True, verbose_name="開放預約日期"
            ),
        ),
    ]
