# Generated by Django 5.1.5 on 2025-09-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coursekit", "0004_coursetemplate_booking_close_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursepricing",
            options={
                "ordering": ["resort", "id"],
                "verbose_name": "5. 課程定價",
                "verbose_name_plural": "5. 課程定價",
            },
        ),
        migrations.AlterUniqueTogether(
            name="coursepricing",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="coursepricing",
            name="templates",
            field=models.ManyToManyField(
                help_text="此定價策略適用的課程模板",
                related_name="pricing_options",
                to="Coursekit.coursetemplate",
                verbose_name="適用課程模板",
            ),
        ),
        migrations.RemoveField(
            model_name="coursepricing",
            name="template",
        ),
    ]
