# Generated by Django 5.1.5 on 2025-10-09 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0001_initial"),
        ("Coursekit", "0005_alter_coursepricing_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecategory",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_categories",
                to="Client.client",
                verbose_name="所屬客戶",
            ),
        ),
    ]
