# Generated by Django 5.1.5 on 2025-11-10 10:37

from django.db import migrations


def fill_null_clients(apps, schema_editor):
    """
    將所有沒有 client 的 CourseCategory 分配給預設的 Client (snowland)
    """
    Client = apps.get_model('Client', 'Client')
    CourseCategory = apps.get_model('Coursekit', 'CourseCategory')

    # 嘗試獲取預設的 Client（internal_code = 'snowland'）
    try:
        default_client = Client.objects.get(internal_code='snowland')
    except Client.DoesNotExist:
        # 如果 snowland 不存在，取第一個 Client
        default_client = Client.objects.first()

        # 如果完全沒有 Client，創建一個預設的
        if not default_client:
            default_client = Client.objects.create(
                name='預設客戶',
                internal_code='default',
                is_active=True
            )

    # 將所有沒有 client 的 CourseCategory 分配給預設 Client
    null_categories = CourseCategory.objects.filter(client__isnull=True)
    updated_count = null_categories.update(client=default_client)

    if updated_count > 0:
        print(f"[OK] 已將 {updated_count} 個 CourseCategory 分配給客戶: {default_client.name} ({default_client.internal_code})")


class Migration(migrations.Migration):

    dependencies = [
        ("Coursekit", "0006_coursecategory_client"),
        ("Client", "0001_initial"),  # 確保 Client app 已經 migrate
    ]

    operations = [
        migrations.RunPython(fill_null_clients, reverse_code=migrations.RunPython.noop),
    ]
