# Generated by Django 5.1.5 on 2025-11-10 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0004_remove_client_aiservice_remove_client_crm_and_more"),
        ("Coursekit", "0007_fill_null_clients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecategory",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_categories",
                to="Client.client",
                verbose_name="所屬客戶",
            ),
        ),
    ]
