# Generated by Django 5.1.5 on 2026-09-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coursekit', '0015_coursetemplate_coach_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetemplate',
            name='billing_mode',
            field=models.CharField(choices=[('private', '包班計價'), ('per_person', '每人計價')], default='private', max_length=20, verbose_name='計價方式'),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='minimum_group_size',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='最低開班人數'),
        ),
        migrations.AddField(
            model_name='coursetemplate',
            name='minimum_student_level',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='學員最低等級'),
        ),
    ]
