# Generated by Django 5.1.5 on 2025-07-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "創建預約"),
                    (1, "已取消"),
                    (9, "無法自動排定教練"),
                    (10, "需人工排定教練"),
                    (20, "已自動排定教練"),
                    (21, "人工手動排定教練"),
                    (30, "已填表單"),
                    (99, "已完成"),
                ],
                default=0,
                verbose_name="預約狀態",
            ),
        ),
    ]
