# Generated by Django 5.1.5 on 2025-07-08 08:39

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "languages",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[("en", "EN"), ("zh", "中文"), ("yue", "廣東")],
                        default="zh",
                        max_length=9,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可接課"),
                ),
                ("img", models.URLField(blank=True, null=True, verbose_name="教練圖片URL")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "教練",
                "verbose_name_plural": "教練基礎設定",
            },
        ),
        migrations.CreateModel(
            name="CoachCourseLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("SNOWBOARD_singleboard", "單板 Snowboard"),
                            ("SKI_doubleboard", "雙板 Ski"),
                            ("Photography", "雪地攝影 Photography"),
                            ("Travel_Photography", "旅行攝影 Travel Photography"),
                        ],
                        max_length=100,
                        verbose_name="課程類型",
                    ),
                ),
                (
                    "ability_levels",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("no_exp", "無經驗"),
                            ("entry", "入門"),
                            ("basic", "初階"),
                            ("intermediate", "中階"),
                            ("advanced", "高階"),
                            ("expert", "專家"),
                        ],
                        max_length=47,
                        null=True,
                        verbose_name="可接課等級",
                    ),
                ),
                (
                    "price_level",
                    models.CharField(
                        choices=[
                            ("Lv1", "Lv1"),
                            ("Lv2", "Lv2"),
                            ("Lv3", "Lv3"),
                            ("director", "校長&總監"),
                        ],
                        max_length=20,
                        verbose_name="價格等級",
                    ),
                ),
            ],
            options={
                "verbose_name": "教練課程等級",
                "verbose_name_plural": "教練課程等級",
            },
        ),
        migrations.CreateModel(
            name="CoachLeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="請假開始日期")),
                ("end_date", models.DateField(verbose_name="請假結束日期")),
                ("reason", models.TextField(verbose_name="請假原因")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待審核"),
                            ("approved", "已批准"),
                            ("rejected", "已拒絕"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "processing_result",
                    models.TextField(blank=True, verbose_name="處理結果"),
                ),
                (
                    "need_notify_customers",
                    models.BooleanField(default=False, verbose_name="需要通知客戶"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="審核時間"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申請時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "教練請假申請",
                "verbose_name_plural": "教練請假申請",
            },
        ),
        migrations.CreateModel(
            name="CoachResort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resort_priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("coach_leave_conflict", "教練請假衝突"),
                            ("no_coach_available", "無教練可排課"),
                            ("scheduling_failed", "排課失敗"),
                            ("customer_notification_needed", "需通知客戶"),
                        ],
                        max_length=30,
                        verbose_name="通知類型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                ("content", models.TextField(verbose_name="內容")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "未讀"),
                            ("read", "已讀"),
                            ("processing", "處理中"),
                            ("resolved", "已解決"),
                        ],
                        default="unread",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="解決時間"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="負責人",
                    ),
                ),
            ],
            options={
                "verbose_name": "管理員通知",
                "verbose_name_plural": "管理員通知",
                "ordering": ["-created_at"],
            },
        ),
    ]
