# Generated by Django 5.1.5 on 2025-07-08 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Coach", "0001_initial"),
        ("Resorts", "0002_resorts_auto_scheduling_enabled"),
        ("booking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adminnotification",
            name="related_reservations",
            field=models.ManyToManyField(
                blank=True, to="booking.reservation", verbose_name="相關預約"
            ),
        ),
        migrations.AddField(
            model_name="coach",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="使用者",
            ),
        ),
        migrations.AddField(
            model_name="coachcourselevel",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_levels",
                to="Coach.coach",
            ),
        ),
        migrations.AddField(
            model_name="coachleaverequest",
            name="affected_reservations",
            field=models.ManyToManyField(
                blank=True, to="booking.reservation", verbose_name="受影響的預約"
            ),
        ),
        migrations.AddField(
            model_name="coachleaverequest",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Coach.coach",
                verbose_name="教練",
            ),
        ),
        migrations.AddField(
            model_name="coachleaverequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_leave_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="審核人",
            ),
        ),
        migrations.AddField(
            model_name="adminnotification",
            name="leave_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Coach.coachleaverequest",
                verbose_name="相關請假申請",
            ),
        ),
        migrations.AddField(
            model_name="coachresort",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Coach.coach"
            ),
        ),
        migrations.AddField(
            model_name="coachresort",
            name="resort",
            field=models.ForeignKey(
                db_column="resort_fk_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="Resorts.resorts",
                verbose_name="雪場",
            ),
        ),
    ]
