# Generated by Django 5.1.5 on 2025-07-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0002_initial'),
    ]

    operations = [
        # 修復 CoachResort 表結構：移除舊的 resort varchar 欄位
        migrations.RunSQL(
            # 移除舊的 NOT NULL resort varchar 欄位
            "ALTER TABLE Coach_coachresort DROP COLUMN resort;",
            # 如果需要回滾，重新添加該欄位（不過通常不需要）
            reverse_sql="ALTER TABLE Coach_coachresort ADD COLUMN resort varchar(100) NOT NULL DEFAULT '';"
        ),
    ]
