# Generated by Django 5.1.5 on 2025-08-26 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resorts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="內部使用的英文或拼音名稱，例如 'Tomamu'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="顯示給使用者看的名稱，例如 '星野 Tomamu'",
                        max_length=100,
                        verbose_name="顯示名稱",
                    ),
                ),
                (
                    "auto_scheduling_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="若勾選，此雪場的預約將會進入自動排課流程。",
                        verbose_name="啟用自動排課",
                    ),
                ),
            ],
            options={
                "verbose_name": "雪場",
                "verbose_name_plural": "雪場",
            },
        ),
        migrations.CreateModel(
            name="ResortFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("coach_director", "校長/總監指定費用"),
                            ("coach_lv2", "二級教練指定費用"),
                            ("coach_general", "一般教練指定費用"),
                            ("language_zh", "中文授課費用"),
                            ("language_en", "英文授課費用"),
                            ("language_yue", "粵語授課費用"),
                            ("equipment_1to3", "1-3人裝備租借費用"),
                            ("equipment_4to6", "4-6人裝備租借費用"),
                        ],
                        max_length=20,
                        verbose_name="費用類型",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="費用金額（新台幣）", verbose_name="價格"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否啟用")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="可選的費用說明文字", verbose_name="費用說明"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="Resorts.resorts",
                        verbose_name="所屬雪場",
                    ),
                ),
            ],
            options={
                "verbose_name": "雪場費用設定",
                "verbose_name_plural": "雪場費用設定",
                "ordering": ["resort", "fee_type"],
                "unique_together": {("resort", "fee_type")},
            },
        ),
    ]
