# Generated by Django 5.1.5 on 2025-10-09 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0001_initial"),
        ("Resorts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resorts",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="此雪場歸屬於哪個客戶",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resorts",
                to="Client.client",
                verbose_name="所屬客戶",
            ),
        ),
    ]
