# Generated by Codex on 2026-06-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resorts', '0006_equipmentassistancetimeslot_course_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Item code')),
                ('name', models.CharField(max_length=120, verbose_name='Item name')),
                ('daily_price', models.PositiveIntegerField(default=0, verbose_name='Daily price')),
                ('additional_day_price', models.PositiveIntegerField(default=0, verbose_name='Additional day price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display order')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                (
                    'resort',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='equipment_rental_items',
                        to='Resorts.resorts',
                        verbose_name='Resort',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Equipment rental add-on item',
                'verbose_name_plural': 'Equipment rental add-on items',
                'ordering': ['resort', 'display_order', 'id'],
                'unique_together': {('resort', 'code')},
            },
        ),
    ]
