# Generated by Django 5.1.5 on 2026-09-02 18:53

import Resorts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_alter_sitecontent_image_url_and_more'),
        ('Resorts', '0007_equipmentrentalitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='校區名稱')),
                ('code', models.SlugField(verbose_name='校區代碼')),
                ('description', models.TextField(blank=True, default='', verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('display_order', models.IntegerField(default=0, verbose_name='顯示順序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='Client.client', verbose_name='所屬客戶')),
                ('resorts', models.ManyToManyField(blank=True, related_name='campuses', to='Resorts.resorts', verbose_name='可使用雪場')),
            ],
            options={
                'verbose_name': '校區',
                'verbose_name_plural': '校區',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperatingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unpaid_hold_days', models.PositiveSmallIntegerField(default=3, verbose_name='未付款保留天數')),
                ('provisional_extra_groups', models.PositiveSmallIntegerField(default=3, verbose_name='未付款容許加排組數')),
                ('cancellation_fee_percent', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='取消手續費百分比')),
                ('cancellation_rules', models.JSONField(blank=True, default=Resorts.models.default_cancellation_rules, verbose_name='退費階梯')),
                ('leave_advance_days', models.PositiveSmallIntegerField(default=3, verbose_name='請假需提前天數')),
                ('leave_daily_coach_limit', models.PositiveSmallIntegerField(default=2, verbose_name='每日請假人數上限')),
                ('leave_max_consecutive_days', models.PositiveSmallIntegerField(default=2, verbose_name='連續請假天數上限')),
                ('course_reminder_days', models.JSONField(blank=True, default=list, verbose_name='課前提醒天數')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='其他營運設定')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operating_policy', to='Resorts.campus', verbose_name='校區')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_policies', to='Client.client', verbose_name='所屬客戶')),
            ],
            options={
                'verbose_name': '營運規則',
                'verbose_name_plural': '營運規則',
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='帳戶名稱')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, verbose_name='銀行名稱')),
                ('bank_branch', models.CharField(blank=True, default='', max_length=100, verbose_name='分行')),
                ('account_number', models.CharField(blank=True, default='', max_length=80, verbose_name='帳號')),
                ('account_holder', models.CharField(blank=True, default='', max_length=100, verbose_name='戶名')),
                ('overseas_details', models.TextField(blank=True, default='', verbose_name='海外匯款資料')),
                ('is_default', models.BooleanField(default=False, verbose_name='預設帳戶')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('display_order', models.IntegerField(default=0, verbose_name='顯示順序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campuses', models.ManyToManyField(blank=True, related_name='payment_accounts', to='Resorts.campus', verbose_name='適用校區')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='Client.client', verbose_name='所屬客戶')),
                ('resorts', models.ManyToManyField(blank=True, related_name='payment_accounts', to='Resorts.resorts', verbose_name='適用雪場')),
            ],
            options={
                'verbose_name': '收款帳戶',
                'verbose_name_plural': '收款帳戶',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('client', 'code'), name='unique_campus_code_per_client'),
        ),
        migrations.AddConstraint(
            model_name='operatingpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('campus__isnull', True)), fields=('client',), name='unique_client_default_operating_policy'),
        ),
    ]
