# Generated by Django 5.1.5 on 2026-09-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resorts', '0008_campus_operatingpolicy_paymentaccount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operatingpolicy',
            name='unique_client_default_operating_policy',
        ),
    ]
