# Generated by Django 5.1.5 on 2025-08-26 11:34

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachLeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="請假開始日期")),
                ("end_date", models.DateField(verbose_name="請假結束日期")),
                ("reason", models.TextField(verbose_name="請假原因")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待審核"),
                            ("approved", "已批准"),
                            ("rejected", "已拒絕"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "processing_result",
                    models.TextField(blank=True, verbose_name="處理結果"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="審核時間"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申請時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "教練請假申請",
                "verbose_name_plural": "教練請假申請",
            },
        ),
        migrations.CreateModel(
            name="CoachResort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resort_priority",
                    models.IntegerField(default=0, verbose_name="雪場優先順序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name": "教練雪場",
                "verbose_name_plural": "教練雪場設定",
            },
        ),
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "languages",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[("en", "EN"), ("zh", "中文"), ("yue", "廣東")],
                        default="zh",
                        max_length=9,
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("active", "主動接課"),
                            ("passive", "需確認接課"),
                            ("unavailable", "不可接課"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="接課狀態",
                    ),
                ),
                (
                    "assignment_score",
                    models.IntegerField(
                        default=0,
                        help_text="分數越低，越優先被系統指派。成功指派後會自動增加。",
                        verbose_name="教練分派權重分數",
                    ),
                ),
                ("img", models.URLField(blank=True, null=True, verbose_name="教練圖片URL")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "教練",
                "verbose_name_plural": "教練基礎設定",
            },
        ),
        migrations.CreateModel(
            name="CoachCourseLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ability_levels",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("no_exp", "無經驗"),
                            ("entry", "入門"),
                            ("basic", "初階"),
                            ("intermediate", "中階"),
                            ("advanced", "高階"),
                            ("expert", "專家"),
                        ],
                        max_length=47,
                        null=True,
                        verbose_name="可接課等級",
                    ),
                ),
                (
                    "price_level",
                    models.CharField(
                        choices=[
                            ("Lv1", "Lv1"),
                            ("Lv2", "Lv2"),
                            ("Lv3", "Lv3"),
                            ("director", "校長&總監"),
                        ],
                        max_length=20,
                        verbose_name="價格等級",
                    ),
                ),
                ("course_order", models.IntegerField(default=0, verbose_name="接課順序")),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_levels",
                        to="Coach.coach",
                    ),
                ),
            ],
            options={
                "verbose_name": "教練課程等級",
                "verbose_name_plural": "教練課程等級",
            },
        ),
    ]
