# Generated by Django 5.1.5 on 2025-08-26 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Coach", "0001_initial"),
        ("Resorts", "0001_initial"),
        ("booking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coachleaverequest",
            name="affected_reservations",
            field=models.ManyToManyField(
                blank=True, to="booking.reservation", verbose_name="受影響的預約"
            ),
        ),
        migrations.AddField(
            model_name="coachleaverequest",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Coach.coach",
                verbose_name="教練",
            ),
        ),
        migrations.AddField(
            model_name="coachleaverequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_leave_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="審核人",
            ),
        ),
        migrations.AddField(
            model_name="coachresort",
            name="coach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Coach.coach",
                verbose_name="教練",
            ),
        ),
        migrations.AddField(
            model_name="coachresort",
            name="resort",
            field=models.ForeignKey(
                db_column="resort_fk_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="Resorts.resorts",
                verbose_name="雪場",
            ),
        ),
    ]
