# Generated by Django 5.1.5 on 2025-08-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0002_initial'),
        ('Courses', '0002_course_resort_coursetemplate_max_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcourselevel',
            name='course_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='Courses.coursetype',
                verbose_name='課程類型'
            ),
        ),
    ]
