# Generated by Django 5.1.5 on 2025-08-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0002_initial'),
        ('Courses', '0002_course_resort_coursetemplate_max_capacity_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE `Coach_coachcourselevel`
                        MODIFY COLUMN `course_type_id` INT NULL,
                        ADD CONSTRAINT `Coach_coachcourselev_course_type_id_fk_Courses_c_final`
                        FOREIGN KEY (`course_type_id`) REFERENCES `Courses_coursetype` (`id`);
                    """,
                    reverse_sql="""
                        ALTER TABLE `Coach_coachcourselevel`
                        DROP FOREIGN KEY `Coach_coachcourselev_course_type_id_fk_Courses_c_final`;
                    """
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='coachcourselevel',
                    name='course_type',
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='Courses.coursetype',
                        verbose_name='課程類型'
                    ),
                ),
            ]
        )
    ]
