# Generated by Django 5.1.5 on 2025-09-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Coach", "0003_coachcourselevel_course_type"),
    ]

    operations = []
