# Generated by Django 5.1.5 on 2025-09-23 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coach", "0004_migrate_course_type_references"),
        ("Coursekit", "0005_alter_coursepricing_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachcourselevel",
            name="course_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Coursekit.coursetype",
                verbose_name="課程類型",
            ),
        ),
    ]
