# Generated by Django 5.1.5 on 2025-10-09 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0001_initial"),
        ("Coach", "0005_alter_coachcourselevel_course_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coaches",
                to="Client.client",
                verbose_name="所屬客戶",
            ),
        ),
    ]
