# Generated by Django 5.1.5 on 2026-09-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0010_update_ability_levels_to_numeric'),
        ('Resorts', '0008_campus_operatingpolicy_paymentaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='campuses',
            field=models.ManyToManyField(blank=True, related_name='coaches', to='Resorts.campus', verbose_name='所屬校區'),
        ),
    ]
