# Generated by Django 5.1.5 on 2026-09-02 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0011_coach_campuses'),
        ('Coursekit', '0016_coursetemplate_billing_mode_and_more'),
        ('Resorts', '0009_remove_operatingpolicy_unique_client_default_operating_policy'),
        ('booking', '0009_initialize_campus_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('course_pay', models.PositiveIntegerField(default=0)),
                ('specified_fees', models.PositiveIntegerField(default=0)),
                ('referral_commission', models.PositiveIntegerField(default=0)),
                ('assistance_pay', models.PositiveIntegerField(default=0)),
                ('supervisor_allowance', models.PositiveIntegerField(default=0)),
                ('adjustment', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已確認'), ('paid', '已發放')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_statements', to='Resorts.campus')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_statements', to='Coach.coach')),
            ],
            options={
                'unique_together': {('coach', 'campus', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('course', '課程時薪'), ('specified', '指定費'), ('referral', '介紹費'), ('assistance', '協助費'), ('allowance', '主管加給'), ('adjustment', '調整')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_lines', to='booking.booking')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='Coach.payrollstatement')),
            ],
        ),
        migrations.CreateModel(
            name='CoachPayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('snowboard', '單板'), ('ski', '雙板'), ('photo', '攝影')], max_length=20)),
                ('certification_level', models.CharField(blank=True, default='', max_length=30)),
                ('hourly_rate', models.PositiveIntegerField(default=0)),
                ('specified_fee', models.PositiveIntegerField(default=0, help_text='每組計算')),
                ('referral_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('assistance_hour_factor', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
                ('supervisor_allowance', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_rules', to='Coach.coach')),
                ('course_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_pay_rules', to='Coursekit.coursetype')),
            ],
            options={
                'unique_together': {('coach', 'course_type', 'discipline', 'certification_level')},
            },
        ),
        migrations.CreateModel(
            name='StaffIncentiveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_order_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_incentive_rules', to='Resorts.campus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snowland_incentive_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'campus')},
            },
        ),
    ]
