# Generated by Django 5.1.5 on 2026-07-19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Client", "0007_alter_sitecontent_image_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatBookingSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("channel", models.CharField(choices=[("api", "Internal API"), ("line", "LINE")], default="api", max_length=20)),
                ("external_user_id", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(choices=[("active", "Active"), ("awaiting_confirmation", "Awaiting confirmation"), ("confirmed", "Confirmed"), ("escalated", "Escalated"), ("completed", "Completed"), ("cancelled", "Cancelled"), ("expired", "Expired")], default="active", max_length=32)),
                ("current_step", models.CharField(blank=True, default="service_type", max_length=64)),
                ("slot_values", models.JSONField(blank=True, default=dict)),
                ("state_version", models.PositiveIntegerField(default=1)),
                ("access_token_hash", models.CharField(max_length=64)),
                ("ai_enabled", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chat_booking_sessions", to="Client.client")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="chat_booking_sessions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="ChatBookingMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("direction", models.CharField(choices=[("inbound", "Inbound"), ("outbound", "Outbound"), ("system", "System")], max_length=16)),
                ("sender_type", models.CharField(choices=[("customer", "Customer"), ("ai", "AI"), ("agent", "Agent"), ("system", "System")], max_length=16)),
                ("content", models.TextField()),
                ("external_message_key", models.CharField(blank=True, max_length=320, null=True, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="chatbooking.chatbookingsession")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="ChatBookingHandoff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("requested", "Requested"), ("assigned", "Assigned"), ("resolved", "Resolved"), ("cancelled", "Cancelled")], default="requested", max_length=16)),
                ("reason", models.TextField(blank=True, default="")),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_chat_booking_handoffs", to=settings.AUTH_USER_MODEL)),
                ("session", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="handoff", to="chatbooking.chatbookingsession")),
            ],
        ),
        migrations.CreateModel(
            name="ChatBookingEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(max_length=20)),
                ("external_event_id", models.CharField(max_length=255)),
                ("payload_hash", models.CharField(blank=True, default="", max_length=64)),
                ("status", models.CharField(choices=[("received", "Received"), ("processing", "Processing"), ("processed", "Processed"), ("failed", "Failed")], default="received", max_length=16)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chat_booking_events", to="Client.client")),
                ("session", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="chatbooking.chatbookingsession")),
            ],
        ),
        migrations.CreateModel(
            name="ChatBookingDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("quoted", "Quoted"), ("committed", "Committed"), ("failed", "Failed")], default="draft", max_length=16)),
                ("cart", models.JSONField(blank=True, default=list)),
                ("contact", models.JSONField(blank=True, default=dict)),
                ("discount_code", models.CharField(blank=True, default="", max_length=100)),
                ("quote", models.JSONField(blank=True, default=dict)),
                ("quote_hash", models.CharField(blank=True, default="", max_length=64)),
                ("quote_expires_at", models.DateTimeField(blank=True, null=True)),
                ("reservation_group_ids", models.JSONField(blank=True, default=list)),
                ("payment_snapshot", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="draft", to="chatbooking.chatbookingsession")),
            ],
        ),
        migrations.CreateModel(
            name="ChatBookingToolInvocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tool_key", models.CharField(max_length=100)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("status", models.CharField(choices=[("processing", "Processing"), ("succeeded", "Succeeded"), ("failed", "Failed")], default="processing", max_length=16)),
                ("input_data", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tool_invocations", to="chatbooking.chatbookingsession")),
            ],
        ),
        migrations.AddIndex(
            model_name="chatbookingsession",
            index=models.Index(fields=["client", "channel", "external_user_id"], name="chatbooking_client__27eb54_idx"),
        ),
        migrations.AddIndex(
            model_name="chatbookingsession",
            index=models.Index(fields=["client", "status", "updated_at"], name="chatbooking_client__b711af_idx"),
        ),
        migrations.AddIndex(
            model_name="chatbookingmessage",
            index=models.Index(fields=["session", "created_at"], name="chatbooking_session_89ab40_idx"),
        ),
        migrations.AddConstraint(
            model_name="chatbookingevent",
            constraint=models.UniqueConstraint(fields=("client", "channel", "external_event_id"), name="chatbooking_unique_external_event"),
        ),
        migrations.AddConstraint(
            model_name="chatbookingtoolinvocation",
            constraint=models.UniqueConstraint(fields=("session", "tool_key", "idempotency_key"), name="chatbooking_unique_tool_invocation"),
        ),
    ]
