# Generated by Django 5.1.5 on 2025-07-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resorts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="內部使用的英文或拼音名稱，例如 'Tomamu'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="顯示給使用者看的名稱，例如 '星野 Tomamu'",
                        max_length=100,
                        verbose_name="顯示名稱",
                    ),
                ),
            ],
            options={
                "verbose_name": "雪場",
                "verbose_name_plural": "雪場",
            },
        ),
    ]
