# Generated by Django 5.1.5 on 2025-07-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Resorts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resorts",
            name="auto_scheduling_enabled",
            field=models.BooleanField(
                default=True, help_text="若勾選，此雪場的預約將會進入自動排課流程。", verbose_name="啟用自動排課"
            ),
        ),
    ]
