# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_permissions',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
