# Generated by Codex on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0002_userprofile_admin_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_service_staff',
            field=models.BooleanField(default=False),
        ),
    ]
