# Generated by Codex on 2026-07-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0003_userprofile_is_service_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_service_staff',
        ),
    ]
