# Generated by Codex on 2026-07-08

from django.conf import settings
from django.db import migrations


def clear_manager_for_superusers(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserProfile = apps.get_model('Control', 'UserProfile')
    superuser_ids = list(User.objects.filter(is_superuser=True).values_list('id', flat=True))
    if superuser_ids:
        UserProfile.objects.filter(user_id__in=superuser_ids, is_manager=True).update(
            is_manager=False,
            admin_permissions=[],
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Control', '0004_remove_userprofile_is_service_staff'),
    ]

    operations = [
        migrations.RunPython(clear_manager_for_superusers, migrations.RunPython.noop),
    ]
