# Generated by Django 5.1.5 on 2026-09-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0005_clear_manager_for_superusers'),
        ('Resorts', '0008_campus_operatingpolicy_paymentaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='campuses',
            field=models.ManyToManyField(blank=True, related_name='staff_profiles', to='Resorts.campus'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('hq_admin', '總部管理員'), ('marketing', '行銷人員'), ('web_editor', '網頁人員'), ('insurance', '保險人員'), ('assistant', '行政小幫手'), ('campus_principal', '校區校長'), ('campus_manager', '校區主管'), ('coach', '教練'), ('photographer', '攝影人員')], default='', max_length=30),
        ),
    ]
