# Generated by Django 5.1.5 on 2025-08-26 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Resorts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="例如：全天5小時教學課程", max_length=100)),
                ("duration", models.CharField(help_text="例如：5小時", max_length=50)),
                ("is_active", models.BooleanField(default=True, help_text="是否啟用此課程模板")),
            ],
            options={
                "verbose_name": "2. 課程模板",
                "verbose_name_plural": "2. 課程模板",
            },
        ),
        migrations.CreateModel(
            name="SeasonSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="季節期間名稱")),
                (
                    "season_type",
                    models.CharField(
                        choices=[("peak", "旺季"), ("off", "淡季")],
                        max_length=10,
                        verbose_name="季節類型",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="開始日期")),
                ("end_date", models.DateField(verbose_name="結束日期")),
            ],
            options={
                "verbose_name": "5. 季節定價設定",
                "verbose_name_plural": "5. 季節定價設定",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(help_text="時段，例如 '全天', '上午'", max_length=20),
                ),
                (
                    "date_range",
                    models.CharField(
                        help_text="適用日期範圍，例如 '(12/01~03/31)'", max_length=50
                    ),
                ),
                (
                    "total_time",
                    models.CharField(help_text="總時間，例如 '09:00-15:00'", max_length=50),
                ),
                (
                    "main_time",
                    models.CharField(
                        help_text="主要教學時間，例如 '09:00-11:30 / 12:30-15:00'", max_length=50
                    ),
                ),
                (
                    "course_specific_info",
                    models.JSONField(blank=True, default=dict, help_text="課程類型特定的額外資訊"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="Courses.coursetemplate",
                        verbose_name="所屬課程模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. 課程時段",
                "verbose_name_plural": "3. 課程時段",
            },
        ),
        migrations.CreateModel(
            name="CourseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="例如：單板 Snowboard", max_length=100)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="數字越小，排序越前面", verbose_name="顯示順序"
                    ),
                ),
                (
                    "resorts",
                    models.ManyToManyField(
                        blank=True,
                        help_text="適用於哪些雪場的列表",
                        to="Resorts.resorts",
                        verbose_name="適用雪場",
                    ),
                ),
            ],
            options={
                "verbose_name": "1. 課程大類",
                "verbose_name_plural": "1. 課程大類",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="coursetemplate",
            name="course_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="Courses.coursetype",
                verbose_name="所屬課程大類",
            ),
        ),
    ]
