# Generated by Django 5.1.5 on 2025-08-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0001_initial"),
        ("Resorts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="resort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="Resorts.resorts",
                verbose_name="開設雪場",
            ),
        ),
        migrations.AddField(
            model_name="coursetemplate",
            name="max_capacity",
            field=models.PositiveIntegerField(
                default=6, help_text="此課程模板的最大人數限制", verbose_name="最大容量"
            ),
        ),
        migrations.CreateModel(
            name="CoursePricingStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_price_off_peak",
                    models.PositiveIntegerField(
                        help_text="淡季時1人的基礎價格", verbose_name="淡季基礎價格"
                    ),
                ),
                (
                    "peak_season_surcharge",
                    models.PositiveIntegerField(
                        help_text="旺季時額外加價的金額", verbose_name="旺季加價"
                    ),
                ),
                (
                    "additional_person_fee",
                    models.PositiveIntegerField(
                        help_text="每增加1人需額外支付的費用", verbose_name="每增加一人費用"
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        help_text="此定價策略的最大人數限制", verbose_name="最大容量"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否啟用")),
                (
                    "resort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_strategies",
                        to="Resorts.resorts",
                        verbose_name="適用雪場",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_strategies",
                        to="Courses.coursetemplate",
                        verbose_name="所屬課程模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "6. 課程定價策略",
                "verbose_name_plural": "6. 課程定價策略",
                "ordering": ["template", "resort"],
                "unique_together": {("template", "resort")},
            },
        ),
    ]
