# Generated by Django 5.1.5 on 2025-08-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Courses", "0002_course_resort_coursetemplate_max_capacity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="period",
        ),
        migrations.RemoveField(
            model_name="course",
            name="total_time",
        ),
    ]
