"""
Django settings for snowland project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import platform
from dotenv import load_dotenv
import pymysql
import boto3
import logging
import requests # <--- 新增這一行

# 基本的日誌配置，確保日誌可以被看到
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

pymysql.install_as_MySQLdb()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 修改 .env 檔案的路徑，指向 snowland 子資料夾
dotenv_path = os.path.join(BASE_DIR, 'snowland', '.env')

if os.path.exists(dotenv_path):
    logger.info(f"正在從 {dotenv_path} 加載 .env 文件...")
    load_dotenv(dotenv_path=dotenv_path)
    logger.info(".env 文件加載完成。")
else:
    logger.warning(f".env 文件未在 {dotenv_path} 找到。應用程式將依賴於系統級環境變數。")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-6m9s&&mrr%$5oie!_2wc-byua$@8c*oggvsef(94lkoil0j4i*"

# SECURITY WARNING: don't run with debug turned on in production!
# if platform.system() == 'Windows':
DEBUG = True
LOCAL_AUTH_BYPASS = os.getenv('SNOWLAND_LOCAL_AUTH_BYPASS', '0') == '1'
RUN_HOST = 'https://dev.flashfalcon.info'
PAYMENT_HOST = 'https://dev.flashfalcon.info/booking/payment/'
# else:
#     DEBUG = False
#     RUN_HOST = 'https://www.flashfalcon.info'
#     PAYMENT_HOST = 'https://www.flashfalcon.info/booking/payment/'
# 允許 ngrok 域名

# 動態獲取 EC2 私有 IP 並添加到 ALLOWED_HOSTS
try:
    ec2_private_ip = requests.get('http://169.254.169.254/latest/meta-data/local-ipv4', timeout=0.1).text
except requests.exceptions.RequestException:
    ec2_private_ip = None

ALLOWED_HOSTS = [
    'dev.flashfalcon.info',
    'djre.ngrok.io',
    'ffreact.ngrok.io',  # 🔥 前端 ngrok 域名
    'localhost',
    '127.0.0.1',
    'snowland-env.eba-n9h9c3r9.ap-northeast-1.elasticbeanstalk.com',
    '.elasticbeanstalk.com',
    '172.31.12.76', # <--- 把日志里报错的 IP 加在这里
]

if ec2_private_ip:
    ALLOWED_HOSTS.append(ec2_private_ip)

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'corsheaders',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',

    'Client.apps.ClientConfig',
    'Coursekit.apps.CoursekitConfig',
    'booking.apps.BookingConfig',
    'chatbooking.apps.ChatBookingConfig',
    'Courses.apps.CoursesConfig',
    'Control.apps.ControlConfig',
    'Coach.apps.CoachConfig',
    'Resorts.apps.ResortsConfig',
    'API.apps.ApiConfig',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware 必須放在這裡
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "snowland.middleware.LocalAuthBypassMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "snowland.urls"

CSRF_TRUSTED_ORIGINS = [
    'https://dev.flashfalcon.info',
    'https://djre.ngrok.io',
    'https://ffreact.ngrok.io',  # 前端 ngrok 域名
    'http://localhost:8999',
    'http://127.0.0.1:8999',
    'http://localhost:3000',  # 前端開發服務器
]

# CORS 設定：允許前端跨域請求
CORS_ALLOWED_ORIGINS = [
    "https://dev.flashfalcon.info",
    "https://ffreact.ngrok.io",  # 前端 ngrok 域名
    "http://localhost:3000",  # React開發服務器
    "http://127.0.0.1:3000",
]

# 允許攜帶cookie進行跨域請求（Google OAuth需要）
CORS_ALLOW_CREDENTIALS = True

# 允許的HTTP方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 允許的請求頭
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-chat-session-token',
    'idempotency-key',
    'jwt',  # 自定義的JWT header
]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# 🔥 跨域 Cookie 設定（前後端分離）
# 因為前後端不同 domain（ffreact.ngrok.io ↔ djre.ngrok.io），跨域用 cookie 必須：
#   SameSite=None + Secure=True（強制 HTTPS）
# 你 dev 環境也是用 ngrok HTTPS，所以這設定 dev/prod 都適用
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False
# CSRF_COOKIE_DOMAIN = None  # 🔥 不設定，讓 Cookie 只綁定到設定它的域名

# 🔥 Django REST Framework 設定
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'booking.authentication.CsrfExemptSessionAuthentication',  # 🔥 跨域 Session 認證（不檢查 CSRF）
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # 預設允許，由各 API 自己控制
    ],
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "snowland.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# 然後用下面這個新的 DATABASES 設定區塊替換掉舊的
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('Mysql_NAME'),
        'USER': os.getenv('Mysql_USER'),
        'PASSWORD': os.getenv('Mysql_PASSWORD'),
        'HOST': os.getenv('Mysql_HOST'),
        'PORT': os.getenv('Mysql_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', default_storage_engine=INNODB"
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "zh-hant"

TIME_ZONE = "Asia/Taipei"

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

if DEBUG:
    STATIC_URL = '/static/'
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
        os.path.join(BASE_DIR, 'templates'),
    ]
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

else:
    # AWS s3
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_REGION = os.getenv('AWS_REGION')
    AWS_S3_FILE_OVERWRITE = True  # 同名檔案是否要覆寫
    # STATIC_URL = 'https://%s.s3.%s.amazonaws.com/static/' % (
    #     AWS_STORAGE_BUCKET_NAME, AWS_REGION)
    STATIC_URL = f'https://ffsystemstatic.s3.us-east-1.amazonaws.com/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

ACCESS_TOKEN_LIFETIME_SEC = 60*60*2
REFRESH_TOKEN_LIFETIME_SEC = 60*60*24
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(seconds=ACCESS_TOKEN_LIFETIME_SEC),
    'REFRESH_TOKEN_LIFETIME': timedelta(seconds=REFRESH_TOKEN_LIFETIME_SEC),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# LOGIN_REDIRECT_URL = 'https://djre.ngrok.io/booking5/'
# LOGOUT_REDIRECT_URL = 'https://djre.ngrok.io/booking6/'

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = 'snowland.adapters.MySocialAccountAdapter'
ACCOUNT_ADAPTER = 'snowland.adapters.MyAccountAdapter'

# 設定allauth使用的HTTP protocol（開發環境用http）
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'METHOD': 'oauth2',
        'VERIFIED_EMAIL': True,
        # APP 設定已移到 Django Admin 的 Social applications
        # 這樣可以動態修改而不用重啟 server
    }
}

# SnowLand AI 客服。API key 只從環境變數載入，不可寫進原始碼。
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-5.6-terra")
OPENAI_TIMEOUT_SECONDS = int(os.getenv("OPENAI_TIMEOUT_SECONDS", "30"))
OPENAI_MAX_OUTPUT_TOKENS = int(os.getenv("OPENAI_MAX_OUTPUT_TOKENS", "1200"))
OPENAI_MAX_TOOL_ROUNDS = int(os.getenv("OPENAI_MAX_TOOL_ROUNDS", "16"))
OPENAI_MAX_CONTEXT_MESSAGES = int(os.getenv("OPENAI_MAX_CONTEXT_MESSAGES", "24"))

# SnowLand LINE Messaging API. One channel is bound to one client_code.
LINE_CHANNEL_SECRET = os.getenv("LINE_CHANNEL_SECRET", "")
LINE_CHANNEL_ACCESS_TOKEN = os.getenv("LINE_CHANNEL_ACCESS_TOKEN", "")
LINE_CLIENT_CODE = os.getenv("LINE_CLIENT_CODE", "")
LINE_API_TIMEOUT_SECONDS = int(os.getenv("LINE_API_TIMEOUT_SECONDS", "10"))
LINE_LOADING_SECONDS = int(os.getenv("LINE_LOADING_SECONDS", "60"))
LINE_SESSION_TTL_DAYS = int(os.getenv("LINE_SESSION_TTL_DAYS", "30"))
LINE_WEBHOOK_MAX_BODY_BYTES = int(
    os.getenv("LINE_WEBHOOK_MAX_BODY_BYTES", str(1024 * 1024))
)
